DELETE_RESPONSE = "ACCEPTED" # FAIL or OK or ACCEPTED
UPDATE_RESPONSE = "ACCEPTED" # FAIL or OK or ACCEPTED
DELAY_TIME_SECONDS = 3 # time to sleep in seconds
PRODUCT_DB_URI = "http://127.0.0.1:5000/"
RESPONSE_AFTER_DELAY = "DO" # do or cancel